### PR TITLE
Task4

### PR DESCRIPTION
**Pull request by SkorykV**
Links to product-service API endpoints:
GET - https://jh16kdf75j.execute-api.eu-west-1.amazonaws.com/dev/products
GET - https://jh16kdf75j.execute-api.eu-west-1.amazonaws.com/dev/products/{productId}
POST - https://jh16kdf75j.execute-api.eu-west-1.amazonaws.com/dev/products
Link to website: https://de9bltgxbvako.cloudfront.net/
Link to FE MR: https://github.com/SkorykV/nodejs-aws-fe/pull/3
Link to swagger: https://app.swaggerhub.com/apis/SkorykV/swagger-for_table_tennis_online_shop/1.0.0
**What is done:**
**Main scope**
- [x] Task 4.1
- [x] Task 4.2
- [x] Task 4.3
- [x] Frontend application is integrated with product service (user could see all products and create new product via frontend)

**Additional (optional) tasks:**
- [x] POST /products lambda function returns error 400 status code if product data is invalid
- [x] All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
- [x] All lambdas do console.log for each incoming requests and their arguments
- [x] Transaction based creation of product (in case stock creation is failed then related to this stock product is not created and not ready to be used by the end user and vice versa)

Expected score: 9/9

### CODE REVIEW

**Comment by helly-fox** [comment]
All home task criteria are done ✅ (small remark https://jh16kdf75j.execute-api.eu-west-1.amazonaws.com/dev/products/1 404 status should be returned)

**Comment by SkorykV** [comment]
> All home task criteria are done ✅ (small remark https://jh16kdf75j.execute-api.eu-west-1.amazonaws.com/dev/products/1 404 status should be returned)

Thanks for comment. Actually, I saw this. it doesn`t return 404 because id should be a uuid, so db query crashes. I`m not sure, if I need to handle this case, but probably I will add specific check for this (I think, it should return 400 for an id that doesn't match uuid format, what do you think?)

**Comment by Max-Korsakov** [comment]
image
Faced an error during product creation

**Comment by Max-Korsakov** [comment]
Also seams that product data validation (POST/products lambda functions returns error 400 status code if product data is invalid) do not implemented

**Comment by SkorykV** [comment]
> Also seams that product data validation (POST/products lambda functions returns error 400 status code if product data is invalid) do not implemented

Strange, somehow it broke in UI, but for me it works in swagger. Could you test it there? Also would be nice, if you tell me, which payload you sent. Thanks!

**Comment by SkorykV** [comment]
> Also seams that product data validation (POST/products lambda functions returns error 400 status code if product data is invalid) do not implemented

fixed UI. I forgot to deploy it. (I don't handle error because it was not specified anywhere, but should see correct error message in window alert now for incorrect data or successfully saved product for correct one). Check it please and let me know

**Comment by Max-Korsakov** [comment]
I just chacked a code and didn't found any backend validation. I still have cors error on the front end during product creation
image

**Comment by SkorykV** [comment]
> I just chacked a code and didn't found any backend validation. I still have cors error on the front end during product creation
> image

hard reset page pls. And validation is handled by serverless.yml:
request:
            schema:
              application/json: ${file(src/serverless/schemas/create_request.json)}
pls check create_request.json for validation schema :)

**Comment by Max-Korsakov** [comment]
Got it, all criteria are fulfilled, 9 points

**Comment by SkorykV** [comment]
> All home task criteria are done ✅ (small remark https://jh16kdf75j.execute-api.eu-west-1.amazonaws.com/dev/products/1 404 status should be returned)

Fixed it, now returns 400 status and {"error":"product id should be uuid"} response

**Pull request merged**
